password:
  reset:
    resetNotification:
      subjectTemplate: "Free IPA Password Reset"
      messageTemplate: |
        Dear $name,
  
        The Free IPA Password Portal received a password reset request 
        for your account at $requestDate. You can follow the link below 
        to fulfill your password reset request; please notify a systems 
        administrator immediately if you did not request a password reset 
        at this time.
  
        Reset link: $resetLink
        Reset token: $resetToken
  
        This link will remain valid until $expirationDate.
  
        Sincerely,
  
        Free IPA Password Portal
  
        Please do not reply to this automated email.

  change:
    changeNotification:
      subjectTemplate: "Free IPA Password Change"
      messageTemplate: |
        Dear $name,
  
        Your password was changed using the FreeIPA Password 
        portal at $date. Please contact a system administrator 
        immediately if you did not change your password at this 
        time.
  
        Sincerely,
  
        Free IPA Password Portal
  
        Please do not reply to this automated email.

  expiration:
    cron: '0 0 9 * * 1-5'
    warningStartDay: 7
  
    expirationNotification:
      subjectTemplate: "Free IPA Password Expiration Warning: <% if (!expired) out.print(daysToExpiry + ' Days') else out.print 'Password Expired' %>"
      messageTemplate: |
        Dear $name,
        <% if (!expired) { %>
        Your FreeIPA password is due to expire in ${daysToExpiry} days. 
        Please change your password at your soonest convenience through
        the Password Portal UI: $webUri.
        <% } else { %>
        Your FreeIPA password has expired. Please change your password
        at your soonest convenience through the Password Portal UI: 
        $webUri.
        <% } %>
        Sincerely,
        
        Free IPA Password Portal
        
        Please do not reply to this automated email
  
    expirationSummary:
      subjectTemplate: "Free IPA Password Expiration Summary: ${entries.size()} expiring user passwords"
      messageTemplate: |
        Hello,
        <% if (entries.size() < 0) { %>
        No users were found with pending password expiration as of: $computeDate
        <% } else { %>
        The following users have expired passwords or passwords expiring in the 
        next $warningStartDay days:
          
          <% for (entry in entries) {
              out.print entry.name + ": " 
              if (!entry.expired) { 
                out.print(entry.daysToExpiry + ' days') 
              } else { 
                out.print 'password expired'
              }
              out.print "\n"
            } 
        } %>
        Sincerely,
        
        Free IPA Password Portal
        
        Please do not reply to this automated email
    

notifications:
  templateDateFormat: "hh:mm a zzz 'on' MMMM dd yyyy"